blank_issues_enabled: false
contact_links:
  - name: ğŸ§‘â€ğŸ’» Â¿BuscÃ¡s Grupo / Integrantes? Â¡PosteÃ¡ ACA!
    url: https://github.com/sisoputnfrba/foro/issues/2011
    about: Post de bÃºsqueda de grupos o integrantes.