blank_issues_enabled: false
# contact_links:
#  - name: Buscas Grupo / Integrantes? Postea ACA!
#    url: https://github.com/sisoputnfrba/foro/issues/:id
#    about: Post de b√∫squeda de grupos o integrantes. 
