blank_issues_enabled: false
contact_links:
  - name: ğŸ‘©â€ğŸ’» Buscas Grupo / Integrantes para el 2c2021? Postea ACA! ğŸ‘¨â€ğŸ’»
    url: https://github.com/sisoputnfrba/foro/issues/2293
    about: Post de bÃºsqueda de grupos o integrantes. 
